name: OpenAPI-Diff

on:
  workflow_call:
    inputs:
      path-filters:
        description: 'JSON array of strings representing path filter expressions, e.g. [\"openapi/**/*.yaml\", \"openapi/**/*.yml\"]'
        type: string
        required: true
        default: > 
          ["openapi/**/*.yaml", "openapi/**/*.yml"]

env:
  GITHUB_SERVER_URL: ${{ github.server_url }}
  GITHUB_REPOSITORY: ${{ github.repository }}
  GITHUB_REF: ${{ github.ref }}
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_WORKSPACE: ${{ github.workspace }}
  CURRENT_HASH: ${{ github.event.after }}
  PREVIOUS_HASH: ${{ github.event.before }}

jobs:
  changed-files:
    name: Detect changed OpenAPI files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.transform-to-matrix.outputs.matrix }}
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Debug
        id: debug
        shell: bash
        run: |
          cd $GITHUB_ACTION_PATH
          pwd
          ls -lisa
      - name: Identify changed OpenAPI files
        id: list-files
        run: $GITHUB_ACTION_PATH/list_changed_files.sh
        shell: bash
        env:
          PATH_FILTERS: ${{ inputs.path-filters }} 
        
      - name: Transform into GitHub matrix (special JSON format)
        id: transform-to-matrix
        run: $GITHUB_ACTION_PATH/transform_to_github_matrix.sh
        shell: bash
        env:
          CHANGED_FILES: ${{ steps.list-files.outputs.changed_files }}
  
  diff-detection:
    name: Diff on OpenAPI file
    needs: changed-files
    if: ${{ toJson(fromJson(needs.changed-files.outputs.matrix)) != '{}' }}
    runs-on: ubuntu-latest
      # Matrix will spawn a separate job instance for every changed file
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.changed-files.outputs.matrix) }}
    env:
      changed_file: ${{ matrix.file }}
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Verify Diffs on OpenAPI File
        id: diff-file
        run: $GITHUB_ACTION_PATH/openapi_diff.sh
        shell: bash
        env:
          CHANGED_FILE: ${{ inputs.changed-file }}
 
